### ISSUE TITLE
Error During Compilation of the App, Not During App Execution!

### ISSUE THREAD

**Issue by AmanRathoreP** [AmanRathoreP/Raspberry-Pi-4-Self-Driving-Vechicle#2]
The encountered build error message is as follows:
```bash
/src/observer_Computer/src/main/java/observer_java_GUI/src/charts_panels/panel_recorder.java:[58,89] incompatible types: java.lang.Comparable<capture#1 of ?> cannot be converted to int
```
The aforementioned error message pertains to line 4 of the code snippet provided below. 
Execution of the code using the command
```bash
mvn exec:java -Dexec.mainClass="observer_java_GUI.app"
```
does not yield any errors. 
However, attempting to build a jar using the command
```bash
mvn clean compile assembly:single
```
results in the aforementioned error. 
The flaw was in introduced in the commit 43fb26acfc62780357b62ff5566165272c901b00. The following code, retrieved from  [this file](https://github.com/AmanRathoreP/Raspberry-Pi-4-Self-Driving-Vechicle/blob/d690930e64b7b3a0cad93af1451f9ca2a38e915d/src/observer_Computer/src/main/java/observer_java_GUI/src/charts_panels/panel_recorder.java) and the compilation error is generated by [this line](https://github.com/AmanRathoreP/Raspberry-Pi-4-Self-Driving-Vechicle/blob/d690930e64b7b3a0cad93af1451f9ca2a38e915d/src/observer_Computer/src/main/java/observer_java_GUI/src/charts_panels/panel_recorder.java#L58).
![issue_shot](https://user-images.githubusercontent.com/93982282/227458229-c1ccd294-12e6-4904-b0b8-e8a273b089c0.png)

**Comment by AmanRathoreP** [comment]
this issue is being fixed in commit e8e9e62b42e5c7890fe83e64c0ea70acc355c53a
